services:
  ubuntu-hotspot:
    image: ubuntu-code-sense
    build:
      context: .  
      dockerfile: Dockerfile  
    container_name: code-sense
    ports:
      - "8888:8888"
    volumes:
      - .:/home
    tty: true

  make-hotspot:
    image: ubuntu-code-sense
    build:
      context: .  
      dockerfile: Dockerfile  
    container_name: code-sense-make
    volumes:
      - ${HOME}/.gitconfig:/home/${USER}/.gitconfig
      - .:/home
    command: ["sh", "/home/make-hotspot.sh"]
    stdin_open: true  
    tty: true         

  display-hotspot:
    image: ubuntu-code-sense
    build:
      context: .  
      dockerfile: Dockerfile  
    container_name: code-sense-display
    ports:
      - "8080:8888"
    volumes:
      - ${HOME}/.gitconfig:/home/${USER}/.gitconfig
      - .:/home
    command: ["sh", "/home/display.sh"]
